Vagrant.configure("2") do |config| 
    config.vm.box = "dummy"
    config.vm.synced_folder "scripts/", "/home/ubuntu/scripts"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :aws do |aws, override|
        aws.region = "us-west-2"
        aws.availability_zone = "us-west-2a"
        aws.instance_type = "t2.micro"
        aws.ami =  "ami-d732f0b7"
        aws.keypair_name = ENV['AWS_SSH_KEYNAME']
        aws.access_key_id = ENV['AWS_ACCESS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET_KEY']
        aws.security_groups = ["ssh-group","honeypot-group"] 
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = ENV['AWS_SSH_KEYPATH']
    end
    config.vm.provision "fix-no-tty", type: "shell" do |s|
      s.privileged = false
      s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end
    config.vm.provision "install-honeypot", type: "shell" do |s|
      s.inline = "chmod +x /home/ubuntu/scripts/bootstrap.sh && sudo /home/ubuntu/scripts/bootstrap.sh; rm -rf /home/ubuntu/scripts"
    end
end
